conda install python pandas numpy matplotlib tqdm scipy

conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch

conda install -c conda-forge pytorch-lightning lightning-bolts torchmetrics torchinfo

pip install torchattacks adversarial-robustness-toolbox git+https://github.com/fra31/auto-attack


