batch_size: 512
class_num: 10
classify_spotlight: false
dataset: cifar10
device: 2
fast_dev_run: false
feature_num: 512
learning_rate: 0.01
loading: false
max_epochs: 5
model: supervised
optimizer: adam
path: /home/kiarash_temp/adversarial-components/huy_Supervised_models_training_CIFAR10/cifar10_logs/resnet18/version_2/checkpoints/best_val_acc_acc_val=95.51.ckpt
regress_latents: false
