batch_size: 512
class_num: 10
dataset: cifar10
device: 3
fast_dev_run: false
feature_num: 512
learning_rate: 0.01
max_epochs: 5
model: simCLR
optimizer: adam
path: ./bolt_self_supervised_training/simclr/simCLR_resnet18_logs_and_chekpoints/lightning_logs/Using_all_of_train_set_400epochs/checkpoints/epoch=380_best_val_loss=5.988133430480957_online_val_acc=0.88.ckpt
