arch: resnet18
batch_size: 512
data_dir: .
dataset: cifar10
exclude_bn_bias: false
feat_dim: 2048
first_conv: false
fp32: false
gaussian_blur: false
gpu: 2
hidden_mlp: 2048
input_height: 32
jitter_strength: 0.5
learning_rate: 0.03
max_epochs: 800
maxpool1: false
num_nodes: 1
num_samples: 45000
num_workers: 16
online_ft: true
optimizer: sgd
warmup_epochs: 10
weight_decay: 0.0005
