arch: resnet18
augmentation_type: original
batch_size: 1024
data_dir: /home/kiarash_temp/adversarial-components/3dident_causal
dataset: 3dident
exclude_bn_bias: true
fast_dev_run: 1
feat_dim: 128
final_lr: 1.0e-06
first_conv: true
fp32: false
gaussian_blur: false
gpus: 4
hidden_mlp: 2048
input_height: 224
jitter_strength: 1
learning_rate: 1.5
max_epochs: 100
max_steps: -1
maxpool1: true
num_nodes: 1
num_samples: 250000
num_workers: 16
online_ft: true
optimizer: lars
random_train: false
start_lr: 0
temperature: 1
warmup_epochs: 10
weight_decay: 1.0e-06
