batch_size: 256
classifier: resnet18
data_dir: ../data
dataset_size: 195
dev: 0
download_weights: 0
gpu_id: 3
learning_rate: 0.01
logger: tensorboard
max_epochs: 200
no_augmentation: true
num_workers: 20
optimizer: sgd
precision: 32
pretrained: 0
test_phase: 0
weight_decay: 0.01
