python simclr/simclr_module.py --dataset cifar10 --arch resnet18 --gpus 1 --batch_size 256 --num_workers 16 --optimizer lar
s --learning_rate 1.5 --exclude_bn_bias --max_epochs 800 --online_ft

arch: resnet18
batch_size: 256
data_dir: .
dataset: cifar10
exclude_bn_bias: true
fast_dev_run: 1
feat_dim: 128
final_lr: 1.0e-06
first_conv: false
fp32: false
gaussian_blur: false
gpus: 1
hidden_mlp: 2048
input_height: 32
jitter_strength: 0.5
learning_rate: 1.5
max_epochs: 800
max_steps: -1
maxpool1: false
num_nodes: 1
num_samples: 45000
num_workers: 16
online_ft: true
optimizer: lars
start_lr: 0
temperature: 0.5
warmup_epochs: 10
weight_decay: 1.0e-06
