batch_size: 512
class_num: 10
classify_spotlight: true
dataset: 3dident
device: 6
fast_dev_run: false
feature_num: 512
learning_rate: 0.01
loading: false
max_epochs: 5
model: supervised
optimizer: adam
path: ./huy_Supervised_models_training_CIFAR10/3dident_logs/resnet18/version_1/checkpoints/best_val_acc_acc_val=99.24.ckpt
regress_latents: false
