batch_size: 256
classifier: resnet18
data_dir: ../data
dev: 0
download_weights: 0
gpu_id: 0
learning_rate: 0.001
logger: tensorboard
max_epochs: 300
num_workers: 20
optimizer: adam
precision: 32
pretrained: 0
test_phase: 0
weight_decay: 0.001
