arch: resnet18
batch_size: 512
data_dir: ..
dataset: cifar10
exclude_bn_bias: true
feat_dim: 2048
fp32: false
gaussian_blur: false
gpu: 3
hidden_mlp: 2048
input_height: 32
jitter_strength: 0.5
learning_rate: 0.001
lmbda: 0.0078125
max_epochs: 800
num_samples: 45000
num_workers: 32
online_ft: true
optimizer: adam
warmup_epochs: 10
weight_decay: 1.0e-06
