batch_size: 512
class_num: 10
dataset: cifar10
device: 3
fast_dev_run: false
feature_num: 512
learning_rate: 0.01
max_epochs: 5
model: simsiam
optimizer: adam
path: ./bolt_self_supervised_training/simsiam/simsiam_resnet18_logs_and_chekpoints/lightning_logs/version_0/checkpoints/epoch=733-best_val_loss_val_loss=-0.9130538105964661.ckpt
