hyperparams: !!python/object:argparse.Namespace
  batch_size: 256
  classifier: resnet18
  data_dir: ../data
  dev: 0
  download_weights: 0
  gpu_id: 1
  learning_rate: 0.01
  logger: tensorboard
  max_epochs: 100
  num_workers: 20
  precision: 32
  pretrained: 0
  test_phase: 0
  weight_decay: 0.01

version: 3
